---
- name: Create a report of all hosts in the inventory
  hosts: all
  gather_facts: yes
- hosts: local
  gather_facts: no
  tasks:
    - template:
        src: hostreport.j2
        dest: /tmp/hostreport.html
